version: "3.4"
services:
  realtime-chat-compose:
    image: realtime-chat-node/base-build
    container_name: realtime-chat-node-container
    restart: always
    ports:
      - 3030:${PORT}
    tty: true
    stdin_open: true
    volumes:
      - node-modules-data:/src/node_modules
    networks:
      - backend
    depends_on:
      - db

  db:
    image: my_postgres 
    container_name: my_db
    ports:
      - 5433:5432
    networks:
      - backend

volumes:
  node-modules-data:

networks:
  backend: