version: "3.4"
services:
  base:
    build:
      context: ./
      dockerfile: ./.docker/Dockerfile
      target: base
      args:
        - env=${ENV}
    image: realtime-chat-node/base-build

  db:
    build:
      context: ./
      dockerfile: ./pql/Dockerfile
      target: db
    image: my_postgres